import type { LucideIcon } from 'lucide-react'
import {
  Banana,
  Beef,
  CakeSlice,
  Candy,
  Carrot,
  ChefHat,
  Cherry,
  Citrus,
  Coffee,
  ConciergeBell,
  Cookie,
  CookingPot,
  Croissant,
  CupSoda,
  Dessert,
  Donut,
  Drumstick,
  EggFried,
  Fish,
  GlassWater,
  Grape,
  Ham,
  Hamburger,
  IceCreamBowl,
  IceCreamCone,
  Milk,
  Pizza,
  Popcorn,
  Popsicle,
  Salad,
  Sandwich,
  Soup,
  Utensils,
  UtensilsCrossed,
  Wheat,
} from 'lucide-react'

export const FOOD_ICONS: Record<string, LucideIcon> = {
  hamburger: Hamburger,
  sandwich: Sandwich,
  fish: Fish,
  soup: Soup,
  'cooking-pot': CookingPot,
  pizza: Pizza,
  'utensils-crossed': UtensilsCrossed,
  utensils: Utensils,
  salad: Salad,
  drumstick: Drumstick,
  beef: Beef,
  ham: Ham,
  'egg-fried': EggFried,
  'cake-slice': CakeSlice,
  dessert: Dessert,
  cookie: Cookie,
  donut: Donut,
  croissant: Croissant,
  'ice-cream-cone': IceCreamCone,
  'ice-cream-bowl': IceCreamBowl,
  popsicle: Popsicle,
  candy: Candy,
  popcorn: Popcorn,
  'cup-soda': CupSoda,
  coffee: Coffee,
  'glass-water': GlassWater,
  milk: Milk,
  cherry: Cherry,
  banana: Banana,
  grape: Grape,
  carrot: Carrot,
  citrus: Citrus,
  wheat: Wheat,
  'chef-hat': ChefHat,
  'concierge-bell': ConciergeBell,
}

export function isFoodIcon(value?: string | null): value is string {
  return Boolean(value && value in FOOD_ICONS)
}
